# Generated by Django 5.0.1 on 2024-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consommateur_id', models.CharField(max_length=200, unique=True)),
                ('bio', models.BooleanField(default=False)),
                ('local', models.BooleanField(default=False)),
                ('sans_gluten', models.BooleanField(default=False)),
                ('vegetarien', models.BooleanField(default=False)),
                ('vegetalien', models.BooleanField(default=False)),
                ('produit1', models.CharField(max_length=200)),
                ('avis1', models.TextField()),
                ('evaluation1', models.IntegerField()),
                ('date_evaluation1', models.DateField()),
                ('produit2', models.CharField(max_length=200)),
                ('avis2', models.TextField()),
                ('evaluation2', models.IntegerField()),
                ('date_evaluation2', models.DateField()),
                ('produit_demande1', models.CharField(max_length=200)),
                ('motif_demande1', models.TextField()),
                ('produit_demande2', models.CharField(max_length=200)),
                ('motif_demande2', models.TextField()),
            ],
            options={
                'db_table': 'consommateur',
            },
        ),
    ]
