# Generated by Django 5.0.1 on 2024-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('prix_moyen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tendance', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('produits', models.CharField(max_length=50)),
                ('dates', models.DateField()),
                ('quantite_disponible', models.IntegerField()),
                ('offres_speciales', models.CharField(max_length=200)),
                ('mois_precedent', models.IntegerField()),
                ('mois_actuel', models.IntegerField()),
                ('unite_quantite', models.CharField(max_length=50)),
                ('sources', models.CharField(max_length=100)),
                ('produit2', models.CharField(max_length=50)),
                ('date2', models.DateField()),
                ('niveau_actuel', models.CharField(max_length=50)),
                ('prevision', models.CharField(max_length=50)),
                ('source2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'market',
            },
        ),
    ]
