# Generated by Django 5.0.1 on 2024-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_data', models.TextField()),
                ('parcelle_id', models.CharField(max_length=100)),
                ('culture', models.CharField(max_length=100)),
                ('variete', models.CharField(max_length=100)),
                ('date_plantation', models.DateField()),
                ('technique_type', models.CharField(max_length=100)),
                ('fertilization', models.CharField(max_length=100)),
                ('irrigation', models.CharField(max_length=100)),
                ('phytopathological_treatments', models.TextField()),
                ('rendement_attendu_valeur', models.FloatField()),
                ('rendement_attendu_unite', models.CharField(max_length=100)),
                ('farmer_id', models.CharField(max_length=100)),
                ('culture_stats', models.TextField()),
                ('annee', models.IntegerField()),
                ('zone_production', models.TextField()),
                ('quantite_recoltee', models.FloatField()),
                ('unite_quantite', models.CharField(max_length=100)),
                ('periode_recolte_debut', models.DateField()),
                ('periode_recolte_fin', models.DateField()),
            ],
            options={
                'db_table': 'agriculteur',
            },
        ),
    ]
